### ISSUE TITLE
Plan the 4th hackathon

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#521]
This would now be the 4th hackathon (1st@KIS, 2nd@KIS, 3rd@Roslin, 4th@KIS)!

The outcome of the hackathon will be a new stable version of SIMplyBee - we should fix lots of little things, including GitHub actions, vignette on CRAN, test spatial stuff, etc. 

* **Papers/Projects**
  - [x] Revise Laura's paper
  - [ ] Plan the spatial paper
  - [ ] Work on the paper for setting individual worker and queen variances
  - [ ] Test run and discuss Slovenian honeybee breeding programme

* **Speed up the package**
  - [ ] Check profiling from @janaobsteter what should we speed up https://github.com/HighlanderLab/SIMplyBee/issues/378
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/513 --> we won't be able to parallelise due to the global `SP` object :(
  - [x] https://github.com/gaynorr/AlphaSimR/issues/107?

* **Testing**
    - [x] Figure how Chris is implementing his tests so that they run as part of R CMD check
    - [x] #120 
    - [x] Implement the above on our side (this will address https://github.com/HighlanderLab/SIMplyBee/issues/86)
    - [x] Add tests for spatial stuff
    - [x] https://github.com/HighlanderLab/SIMplyBee/issues/100
    - [x] https://github.com/HighlanderLab/SIMplyBee/issues/209
    - [x] break and fix vignettes (problem with the .ignore F2*)  

* **Website**
    - [x] Update website and document this process https://github.com/HighlanderLab/SIMplyBee/issues/497
    - [x] Ensure all vignettes are on the website and on CRAN (for example see https://github.com/HighlanderLab/SIMplyBee/issues/506)
    - [x] https://github.com/HighlanderLab/SIMplyBee/issues/446

* **Polish the package**
    - [x] https://github.com/HighlanderLab/SIMplyBee/issues/540
    - [x] https://github.com/HighlanderLab/SIMplyBee/issues/170
    - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/522
    - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/529

* **GitHub actions**
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/514
  - [x] R CMD check on push https://github.com/HighlanderLab/SIMplyBee/issues/83
  - [x] Publish/Redo website?
  - [ ] Code formatting https://github.com/HighlanderLab/SIMplyBee/issues/129 https://github.com/HighlanderLab/SIMplyBee/issues/309

* **Minor bits**
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/10
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/511
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/512
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/515
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/516
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/524
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/504
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/496
  - [x] https://github.com/HighlanderLab/SIMplyBee/issues/494
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/462
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/450
  - [ ] https://github.com/HighlanderLab/SIMplyBee/issues/519

**Comment by gregorgorjanc** [comment]
This would now be the 4th hackathon (1st@KIS, 2nd@KIS, 3rd@Roslin, 4th@KIS)!

**Comment by gregorgorjanc** [comment]
* The outcome of the hackathon will be a new stable version of SIMplyBee - we should fix lots of little things, including GitHub actions, vignette on CRAN, test spatial stuff, etc. 
* Plan the spatial paper
* Work on the paper for setting individual worker and queen variances
* Test run and discuss Slovenian honeybee breeding programme
* Identify computational bottlenecks for future work and make plan of solving them(@janaobsteter has done some profiling already)

**Comment by gregorgorjanc** [comment]
We should try the parallelisation stuff https://github.com/HighlanderLab/SIMplyBee/issues/513

**Comment by gregorgorjanc** [comment]
* Check profiling from @janaobsteter what should we speed up
* Speed-up setMisc/getMisc in AlphaSimR https://github.com/gaynorr/AlphaSimR/issues/107?

**Comment by gregorgorjanc** [comment]
GitHub actions
https://github.com/HighlanderLab/SIMplyBee/issues/514
https://github.com/HighlanderLab/SIMplyBee/issues/521

**Comment by gregorgorjanc** [comment]
Update website and document this process https://github.com/HighlanderLab/SIMplyBee/issues/497

**Comment by gregorgorjanc** [comment]
Closing this - some issues will be addressed in https://github.com/HighlanderLab/SIMplyBee/issues/588
